import { Memory, Profile } from './types';

export const DEMO_PROFILES: Record<string, Profile> = {
  kartik: {
    id: 'usr-001',
    username: 'kartik_nistane',
    display_name: 'Kartik Nistane',
    avatar_url: 'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?w=150&auto=format&fit=crop&q=80',
    bio: 'Archivist of quiet street corners, analog film, and neighborhood memories from Nagpur.',
    created_at: '2024-01-15T10:00:00Z',
  },
  maya: {
    id: 'usr-001',
    username: 'kartik_nistane',
    display_name: 'Kartik Nistane',
    avatar_url: 'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?w=150&auto=format&fit=crop&q=80',
    bio: 'Archivist of quiet street corners, analog film, and neighborhood memories from Nagpur.',
    created_at: '2024-01-15T10:00:00Z',
  },
  lucas: {
    id: 'usr-002',
    username: 'lucas_pereira',
    display_name: 'Lucas Pereira',
    avatar_url: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    bio: 'Lisbon native, tram sound collector, and seeker of sunset miradouros.',
    created_at: '2024-02-10T14:30:00Z',
  },
  elena: {
    id: 'usr-003',
    username: 'elena_v',
    display_name: 'Elena Vance',
    avatar_url: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&auto=format&fit=crop&q=80',
    bio: 'Flâneuse in Paris. Collecting handwritten bookstore notes and courtyard memories.',
    created_at: '2024-03-01T09:15:00Z',
  },
  kenji: {
    id: 'usr-004',
    username: 'kenji_sato',
    display_name: 'Kenji Sato',
    avatar_url: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
    bio: 'Kyoto craftsman & nocturnal soundscape recorder.',
    created_at: '2024-03-12T16:45:00Z',
  },
  samira: {
    id: 'usr-005',
    username: 'samira_m',
    display_name: 'Samira Merchant',
    avatar_url: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=150&auto=format&fit=crop&q=80',
    bio: 'Mumbai seaside wanderer, monsoon chronicler, and chai enthusiast.',
    created_at: '2024-04-05T11:20:00Z',
  },
};

export const INITIAL_MEMORIES: Memory[] = [
  {
    id: 'mem-100',
    user_id: 'usr-001',
    user: DEMO_PROFILES.kartik,
    place_id: 'plc-100',
    place: {
      id: 'plc-100',
      name: 'Futala Lake Promenade',
      address: 'Futala Lake, Vayusena Nagar, Nagpur, Maharashtra 440001',
      latitude: 21.1539,
      longitude: 79.0494,
    },
    original_text: `Evenings at Futala Lake have a special kind of warmth. When the summer heat softens just before twilight, the lake breeze brings the aroma of freshly roasted bhutta rubbed with lemon and chili from the roadside stalls. My friends and I used to sit on the stone embankment with steaming glasses of cutting chai, debating college projects and music while the colored fountains lit up the gentle ripples on the water. No matter where in the world I travel, that quiet lake breeze feels like home.`,
    ai_title: 'Twilight Chai and Lake Breezes at Futala',
    ai_summary: 'An evening reflection along the stone promenade of Nagpur’s Futala Lake, savoring roasted corn, cutting chai, and golden sunset reflections with lifelong friends.',
    tags: ['Nagpur Stories', 'Futala Lake', 'Chai Rituals', 'Sunset Breezes', 'Orange City'],
    mood: 'Nostalgic',
    visibility: 'public',
    status: 'approved',
    audio_url: 'https://cdn.freesound.org/previews/512/512134_6142149-lq.mp3',
    audio_duration: 36,
    illustration_url: 'https://images.unsplash.com/photo-1506744038136-46273834b3fb?w=1200&auto=format&fit=crop&q=80',
    is_postcard_generated: true,
    media: [
      {
        id: 'med-100',
        memory_id: 'mem-100',
        type: 'photo',
        url: 'https://images.unsplash.com/photo-1506744038136-46273834b3fb?w=1200&auto=format&fit=crop&q=80',
      },
    ],
    reactions_count: { heart: 78, warmth: 52, pin: 34 },
    user_reaction: 'heart',
    is_saved: true,
    comments_count: 4,
    comments: [
      {
        id: 'comm-100a',
        memory_id: 'mem-100',
        user_id: 'usr-005',
        user: DEMO_PROFILES.samira,
        content: 'Futala sunsets with roasted bhutta are truly unmatched in Maharashtra!',
        created_at: '2024-05-10T17:20:00Z',
      },
    ],
    created_at: '2024-05-08T18:30:00Z',
  },
  {
    id: 'mem-101',
    user_id: 'usr-001',
    user: DEMO_PROFILES.kartik,
    place_id: 'plc-101',
    place: {
      id: 'plc-101',
      name: 'Caffe Reggio',
      address: '119 MacDougal St, New York, NY 10012',
      latitude: 40.7301,
      longitude: -73.9996,
    },
    original_text: `Back in the winter of 2018, my grandfather brought me here for my first real espresso. The steam hissing from that towering 1902 chrome and bronze machine felt like the soundtrack of Greenwich Village. He pointed to the small corner bench and told me how he and my grandmother used to split a single cannoli while arguing about poetry in the sixties. Now, whenever I come back on snowy afternoons, the marble tables are still cold to the touch, and the cinnamon smell carries that exact afternoon right back to life.`,
    ai_title: 'The Chrome Espresso Machine of Greenwich Village',
    ai_summary: 'A granddaughter revisits the century-old Italian cafe where her grandfather introduced her to espresso and family memories from the 1960s. The hiss of the 1902 antique machine and cinnamon scent keep their shared history alive.',
    tags: ['Village Life', 'Coffee Rituals', 'Family Heritage', 'Winter in NYC', 'Beat Generation'],
    mood: 'Nostalgic',
    visibility: 'public',
    status: 'approved',
    audio_url: 'https://cdn.freesound.org/previews/512/512134_6142149-lq.mp3',
    audio_duration: 38,
    illustration_url: 'https://images.unsplash.com/photo-1501339847302-ac426a4a7cbb?w=1200&auto=format&fit=crop&q=80',
    is_postcard_generated: false,
    media: [
      {
        id: 'med-101',
        memory_id: 'mem-101',
        type: 'photo',
        url: 'https://images.unsplash.com/photo-1501339847302-ac426a4a7cbb?w=1200&auto=format&fit=crop&q=80',
      },
    ],
    reactions_count: { heart: 42, warmth: 29, pin: 18 },
    user_reaction: 'heart',
    is_saved: true,
    comments_count: 5,
    comments: [
      {
        id: 'comm-1',
        memory_id: 'mem-101',
        user_id: 'usr-002',
        user: DEMO_PROFILES.lucas,
        content: 'I sat at that exact small corner table last October! That machine is truly a historical treasure.',
        created_at: '2024-04-18T14:20:00Z',
      },
      {
        id: 'comm-2',
        memory_id: 'mem-101',
        user_id: 'usr-003',
        user: DEMO_PROFILES.elena,
        content: 'Such a tender memory. The sensory details of the cold marble and cinnamon are vivid.',
        created_at: '2024-04-19T09:12:00Z',
      },
    ],
    created_at: '2024-04-15T16:30:00Z',
  },
  {
    id: 'mem-102',
    user_id: 'usr-003',
    user: DEMO_PROFILES.elena,
    place_id: 'plc-102',
    place: {
      id: 'plc-102',
      name: 'Shakespeare and Company',
      address: '37 Rue de la Bûcherie, 75005 Paris, France',
      latitude: 48.8526,
      longitude: 2.347,
    },
    original_text: `I spent three nights as a 'tumbleweed' upstairs in 2017, sleeping on a bench between ceiling-high towers of poetry and philosophy. Every morning before the shop opened, the bells of Notre-Dame across the Seine rang out like bronze thunder. We had to write a one-page autobiography for George Whitman's archives before we were allowed to sleep there. In the quiet hours past 2 AM, with only the creaking timber floorboards and a sleepy shop cat named Aggie, it felt like time stopped existing.`,
    ai_title: 'Beds in the Stacks and Cathedral Bells',
    ai_summary: 'A former traveler reflects on three nights staying as a tumbleweed above the iconic Parisian bookstore. Between dusty paperbacks and the morning chime of Notre-Dame, the experience captured the ageless bohemian spirit of Paris.',
    tags: ['Bookstore', 'Literary Paris', 'Tumbleweeds', 'Notre Dame', 'Bohemian Life'],
    mood: 'History',
    visibility: 'public',
    status: 'approved',
    audio_url: 'https://cdn.freesound.org/previews/467/467439_9961300-lq.mp3',
    audio_duration: 52,
    illustration_url: 'https://images.unsplash.com/photo-1526778548025-fa2f459cd5c1?w=1200&auto=format&fit=crop&q=80',
    is_postcard_generated: true,
    media: [
      {
        id: 'med-102',
        memory_id: 'mem-102',
        type: 'photo',
        url: 'https://images.unsplash.com/photo-1526778548025-fa2f459cd5c1?w=1200&auto=format&fit=crop&q=80',
      },
    ],
    reactions_count: { heart: 88, warmth: 45, pin: 36 },
    user_reaction: null,
    is_saved: false,
    comments_count: 3,
    comments: [
      {
        id: 'comm-3',
        memory_id: 'mem-102',
        user_id: 'usr-001',
        user: DEMO_PROFILES.maya,
        content: 'Living among the books is every literature lover’s dream. Aggie the cat was legendary!',
        created_at: '2024-04-20T11:05:00Z',
      },
    ],
    created_at: '2024-04-18T10:15:00Z',
  },
  {
    id: 'mem-103',
    user_id: 'usr-002',
    user: DEMO_PROFILES.lucas,
    place_id: 'plc-103',
    place: {
      id: 'plc-103',
      name: 'Miradouro de Santa Luzia',
      address: 'Largo Santa Luzia, 1100-487 Lisboa, Portugal',
      latitude: 38.7118,
      longitude: -9.1306,
    },
    original_text: `The afternoon sun turns Alfama’s terracotta roofs into molten copper. Last May, an elderly gentleman with a weathered Portuguese guitar sat beneath the bougainvillea trellis. Without speaking a word, he played a mournful fado melody that made everyone leaning over the azulejos stop and whisper. I took my partner’s hand, and we watched the ferries glide across the silver Tagus River until the first streetlights flickered on.`,
    ai_title: 'Bougainvillea Sunset and Fado Above the Tagus',
    ai_summary: 'An impromptu fado performance beneath blooming bougainvillea creates an unforgettable romantic twilight overlooking the red-tiled roofs of Alfama and the Tagus river.',
    tags: ['Alfama', 'Fado Guitar', 'Lisbon Sunset', 'Azulejos', 'Miradouro View'],
    mood: 'Romance',
    visibility: 'public',
    status: 'approved',
    audio_url: 'https://cdn.freesound.org/previews/458/458021_9302511-lq.mp3',
    audio_duration: 45,
    illustration_url: 'https://images.unsplash.com/photo-1513581166391-887a96ddeafd?w=1200&auto=format&fit=crop&q=80',
    is_postcard_generated: false,
    media: [
      {
        id: 'med-103',
        memory_id: 'mem-103',
        type: 'photo',
        url: 'https://images.unsplash.com/photo-1513581166391-887a96ddeafd?w=1200&auto=format&fit=crop&q=80',
      },
    ],
    reactions_count: { heart: 67, warmth: 38, pin: 25 },
    user_reaction: 'warmth',
    is_saved: true,
    comments_count: 2,
    comments: [],
    created_at: '2024-04-22T18:40:00Z',
  },
  {
    id: 'mem-104',
    user_id: 'usr-004',
    user: DEMO_PROFILES.kenji,
    place_id: 'plc-104',
    place: {
      id: 'plc-104',
      name: 'Tatsumi Bridge, Gion',
      address: 'Gion Shirakawa, Higashiyama Ward, Kyoto 605-0087',
      latitude: 35.0062,
      longitude: 135.7738,
    },
    original_text: `Rain in Gion has a specific pitch. At midnight, when tourists have cleared out, the water trickles through weeping willows straight into the Shirakawa canal. I stood by the vermilion Tatsumi Shrine railing and closed my eyes: the only sound was the canal current and the crisp, rhythmic 'clack-clack' of paulownia geta sandals fading around a dark wooden machiya bend. It is the secret Kyoto that only reveals itself in darkness.`,
    ai_title: 'Midnight Rain on the Weeping Willows of Shirakawa',
    ai_summary: 'In the quiet midnight rain along Kyoto’s Shirakawa canal, an artisan captures the timeless resonance of flowing water and wooden geta clacking against wet stone pavers.',
    tags: ['Kyoto Rain', 'Shirakawa Canal', 'Soundscape', 'Hidden Alleyways', 'Machiya'],
    mood: 'Hidden Gem',
    visibility: 'public',
    status: 'approved',
    audio_url: 'https://cdn.freesound.org/previews/416/416710_5121236-lq.mp3',
    audio_duration: 30,
    illustration_url: 'https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?w=1200&auto=format&fit=crop&q=80',
    is_postcard_generated: true,
    media: [
      {
        id: 'med-104',
        memory_id: 'mem-104',
        type: 'photo',
        url: 'https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?w=1200&auto=format&fit=crop&q=80',
      },
    ],
    reactions_count: { heart: 94, warmth: 60, pin: 51 },
    user_reaction: 'pin',
    is_saved: true,
    comments_count: 4,
    comments: [],
    created_at: '2024-04-25T01:10:00Z',
  },
  {
    id: 'mem-105',
    user_id: 'usr-001',
    user: DEMO_PROFILES.maya,
    place_id: 'plc-105',
    place: {
      id: 'plc-105',
      name: 'City Lights Bookstore',
      address: '261 Columbus Ave, San Francisco, CA 94133',
      latitude: 37.7976,
      longitude: -122.4066,
    },
    original_text: `College midterms week, autumn 2015. I couldn't bear the sterile university library fluorescent lamps anymore. I hopped on the 30 Stockton bus up to North Beach and hid out in the Poet's Room upstairs at City Lights. The sign reads: 'Have a seat and read a book you haven't bought.' I sat in that wicker chair with a cold thermos of tea, reading Ferlinghetti while cable car bells chimed two blocks away. That afternoon taught me that literature belongs to people on street corners.`,
    ai_title: 'Sanctuary in the Poet’s Room Upstairs',
    ai_summary: 'Fleeing midterms, a college student finds refuge in City Lights Bookstore’s legendary Poet’s Room, discovering how Ferlinghetti and cable car bells transformed reading into a communal sanctuary.',
    tags: ['Beat Poetry', 'North Beach SF', 'Student Midterms', 'Sanctuary Spaces', 'Paperbacks'],
    mood: 'Student Life',
    visibility: 'public',
    status: 'approved',
    audio_url: 'https://cdn.freesound.org/previews/381/381382_1676145-lq.mp3',
    audio_duration: 41,
    illustration_url: 'https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?w=1200&auto=format&fit=crop&q=80',
    is_postcard_generated: false,
    media: [
      {
        id: 'med-105',
        memory_id: 'mem-105',
        type: 'photo',
        url: 'https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?w=1200&auto=format&fit=crop&q=80',
      },
    ],
    reactions_count: { heart: 53, warmth: 31, pin: 22 },
    user_reaction: null,
    is_saved: false,
    comments_count: 1,
    comments: [],
    created_at: '2024-04-27T17:15:00Z',
  },
  {
    id: 'mem-106',
    user_id: 'usr-005',
    user: DEMO_PROFILES.samira,
    place_id: 'plc-106',
    place: {
      id: 'plc-106',
      name: 'Marine Drive Promenade',
      address: 'Marine Drive, Nariman Point, Mumbai, Maharashtra 400020',
      latitude: 18.9438,
      longitude: 72.8234,
    },
    original_text: `July in Mumbai means monsoon spray. My college friends and I used to sit on the giant concrete tetrapods along the Queen’s Necklace after our final exams. The rain would come down sideways from the Arabian Sea, drenching our kurtas in seconds. Cutting chai sellers in yellow plastic tarps poured cardamom tea from steaming aluminium kettles into cutting glasses. We had no money and no clear idea what our careers would be, but sipping that burning hot chai against the icy ocean spray felt invincible.`,
    ai_title: 'Cutting Chai and Monsoon Spray on the Queen’s Necklace',
    ai_summary: 'Friends gather on Mumbai’s Marine Drive tetrapods during torrential monsoon season, drinking hot cardamom tea as ocean waves crash against the promenade.',
    tags: ['Mumbai Monsoon', 'Queen’s Necklace', 'Cutting Chai', 'Seaside Memories', 'Friendship'],
    mood: 'Food',
    visibility: 'public',
    status: 'approved',
    audio_url: 'https://cdn.freesound.org/previews/243/243763_4486188-lq.mp3',
    audio_duration: 35,
    illustration_url: 'https://images.unsplash.com/photo-1570168007204-dfb528c6958f?w=1200&auto=format&fit=crop&q=80',
    is_postcard_generated: false,
    media: [
      {
        id: 'med-106',
        memory_id: 'mem-106',
        type: 'photo',
        url: 'https://images.unsplash.com/photo-1570168007204-dfb528c6958f?w=1200&auto=format&fit=crop&q=80',
      },
    ],
    reactions_count: { heart: 112, warmth: 74, pin: 49 },
    user_reaction: 'heart',
    is_saved: true,
    comments_count: 6,
    comments: [],
    created_at: '2024-05-02T19:00:00Z',
  },
];

export const MOOD_CONFIG: Record<string, { label: string; color: string; bg: string; border: string; markerColor: string; icon: string }> = {
  'Nostalgic': {
    label: 'Nostalgic',
    color: 'text-amber-800',
    bg: 'bg-amber-50',
    border: 'border-amber-300',
    markerColor: '#D97706',
    icon: 'History',
  },
  'Food': {
    label: 'Food',
    color: 'text-orange-800',
    bg: 'bg-orange-50',
    border: 'border-orange-300',
    markerColor: '#EA580C',
    icon: 'Utensils',
  },
  'Hidden Gem': {
    label: 'Hidden Gem',
    color: 'text-emerald-800',
    bg: 'bg-emerald-50',
    border: 'border-emerald-300',
    markerColor: '#059669',
    icon: 'Compass',
  },
  'Student Life': {
    label: 'Student Life',
    color: 'text-blue-800',
    bg: 'bg-blue-50',
    border: 'border-blue-300',
    markerColor: '#2563EB',
    icon: 'GraduationCap',
  },
  'History': {
    label: 'History',
    color: 'text-stone-800',
    bg: 'bg-stone-100',
    border: 'border-stone-300',
    markerColor: '#57534E',
    icon: 'BookOpen',
  },
  'Romance': {
    label: 'Romance',
    color: 'text-rose-800',
    bg: 'bg-rose-50',
    border: 'border-rose-300',
    markerColor: '#E11D48',
    icon: 'Heart',
  },
  'Nature': {
    label: 'Nature',
    color: 'text-teal-800',
    bg: 'bg-teal-50',
    border: 'border-teal-300',
    markerColor: '#0D9488',
    icon: 'Trees',
  },
};
